### ISSUE TITLE
iclx:0.1.2 transformer_engine error

### ISSUE THREAD

**Issue by nemodleo** [nemodleo/attentionx-icl#2]
```
root@workspace-2ukudtzxvxxo-0:~/attentionx-icl# make run-sst2
python scripts/sst2.py
Traceback (most recent call last):
  File "/root/attentionx-icl/scripts/sst2.py", line 6, in <module>
    from iclx import DatasetReader
  File "/root/attentionx-icl/iclx/__init__.py", line 1, in <module>
    from .retriever import BaseRetriever, RandomRetriever
  File "/root/attentionx-icl/iclx/retriever/__init__.py", line 1, in <module>
    from .base_retriever import BaseRetriever
  File "/root/attentionx-icl/iclx/retriever/base_retriever.py", line 5, in <module>
    from accelerate import Accelerator
  File "/usr/local/lib/python3.10/dist-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/usr/local/lib/python3.10/dist-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/__init__.py", line 153, in <module>
    from .launch import (
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/launch.py", line 33, in <module>
    from ..utils.other import is_port_in_use, merge_dicts
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/other.py", line 36, in <module>
    from .transformer_engine import convert_model
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/transformer_engine.py", line 21, in <module>
    import transformer_engine.pytorch as te
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/__init__.py", line 6, in <module>
    from .module import LayerNormLinear
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/module/__init__.py", line 6, in <module>
    from .layernorm_linear import LayerNormLinear
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/module/layernorm_linear.py", line 15, in <module>
    from .. import cpp_extensions as tex
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/cpp_extensions/__init__.py", line 6, in <module>
    from transformer_engine_extensions import *
ImportError: /usr/local/lib/python3.10/dist-packages/transformer_engine_extensions.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
make: *** [Makefile:14: run-sst2] Error 1
```

**Comment by nemodleo** [comment]
```
root@workspace-2ukudtzxvxxo-0:~/attentionx-icl# poetry run python scripts/sst2.py


Downloading data: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 523k/523k [00:01<00:00, 442kB/s]
Downloading data: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 67.7k/67.7k [00:00<00:00, 202kB/s]
Downloading data: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 138k/138k [00:00<00:00, 171kB/s]
Generating train split: 100%|██████████████████████████████████████████████████████████████████████████| 6920/6920 [00:00<00:00, 874787.78 examples/s]
Generating validation split: 100%|███████████████████████████████████████████████████████████████████████| 872/872 [00:00<00:00, 723384.71 examples/s]
Generating test split: 100%|██████████████████████████████████████████████████████████████████████████| 1821/1821 [00:00<00:00, 1113061.44 examples/s]
config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 762/762 [00:00<00:00, 6.09MB/s]
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
model.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 353M/353M [00:17<00:00, 20.4MB/s]
generation_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 124/124 [00:00<00:00, 720kB/s]
vocab.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 1.04M/1.04M [00:00<00:00, 4.57MB/s]
merges.txt: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 456k/456k [00:00<00:00, 738kB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 1.36M/1.36M [00:00<00:00, 5.77MB/s]
2024-02-16 02:10:56.911 | INFO     | iclx.retriever.random_retriever:retrieve:47 - Retrieving data for test set...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 1821/1821 [00:00<00:00, 72970.55it/s]
2024-02-16 02:10:57.900 | INFO     | iclx.inferencer.ppl_inferencer:inference:94 - Calculating PPL for prompts labeled '0'
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1821/1821 [00:10<00:00, 181.16it/s]
2024-02-16 02:11:08.021 | INFO     | iclx.inferencer.ppl_inferencer:inference:94 - Calculating PPL for prompts labeled '1'
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1821/1821 [00:09<00:00, 193.11it/s]
Downloading builder script: 100%|████████████████████████████████████████████████████████████████████████████████| 4.20k/4.20k [00:00<00:00, 17.5MB/s]
{'accuracy': 0.5090609555189456}
```

poetry 에서는 정상작동, 이슈 docker 에서 발생

**Comment by nemodleo** [comment]
`pip uninstall transformer-engine` 으로 해결

**Comment by nemodleo** [comment]
already resolved
