### ISSUE TITLE
AttributeError: 'ParentInferencer' object has no attribute '_ParentInferencer__get_ppl'

### ISSUE THREAD

**Issue by nemodleo** [nemodleo/attentionx-icl#31]
in `develop`
```
Traceback (most recent call last):
  File "/Users/nemo/Documents/attentionx/attentionx-icl/scripts/create_train_with_pseudo.py", line 92, in <module>
    create_data()
  File "/Users/nemo/Documents/attentionx/attentionx-icl/scripts/create_train_with_pseudo.py", line 45, in create_data
    predictions = inferencer.inference(retriever, ice_template=template)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nemo/Documents/attentionx/attentionx-icl/iclx/inferencer/parent_inferencer.py", line 127, in inference
    sub_res = self.__get_ppl(sub_prompt_list).tolist()
              ^^^^^^^^^^^^^^
AttributeError: 'ParentInferencer' object has no attribute '_ParentInferencer__get_ppl'. Did you mean: '_PPLInferencer__get_ppl'?
```

**Comment by nemodleo** [comment]
because of **name mangling**, that prevent overidding their parents' method
